version: '3.3'
services:
  tournament-backend:
    container_name: tournament-backend
    image: thomasherve/tournament-backend
    ports:
      - 4000:3000
    restart: always
  db:
    container_name: tournament-db
    image: postgres
    healthcheck:
      test: "exit 0"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/posgresql/data
    restart: always
    

volumes:
  pgdata: