version: '3.3'
services:
  tournament-backend:
    container_name: tournament-backend
    image: thomasherve/tournament-backend
    restart: always
  db:
    container_name: tournament-db
    image: postgres
    healthcheck:
      test: "exit 0"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/posgresql/data
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/bundle.crt:/etc/ssl/bundle.crt:ro
      - ./nginx/private.key:/etc/ssl/private.key:ro
    depends_on:
      - tournament-backend

volumes:
  pgdata: