name: 'Main'

on:
  push:
    branches:
    - "main"
    - "docker"

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: create docker buildx worker
      run: docker buildx create --platform linux/arm64,linux/amd64,linux/armhf --use --buildkitd-flags '--allow-insecure-entitlement security.insecure' --name tournament-backend

    - name: Connect to dockerhub
      run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build the Docker image
      run: docker build --pull -t ${{secrets.DOCKER_LOGIN}}/tournament-backend --output type=registry .
